
# trigger Pybuda pipeline when master branch is pushed or MR is created
push_integration_tests_pybuda:
  stage: integration
  variables:
    TT_BBE_COMMIT_SHA: "$CI_COMMIT_SHA"
    TT_TRIGGER: "integration"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_REF_NAME == "master"
  trigger:
    project: tenstorrent/pybuda
    branch: main

# trigger Pybuda pipelin from scheduled pipelines
nightly_integration_tests_pybuda:
  stage: integration
  variables:
    TT_BBE_COMMIT_SHA: "$CI_COMMIT_SHA"
    TT_TRIGGER: "integration"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_REF_NAME == "master"
  trigger:
    project: tenstorrent/pybuda
    branch: main